version: '3'

services:
  app:
    build: ./app
    ports:
      - 3000:3000
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=user-expenses
      - DB_HOST=db
      - JWT_SECRET=878d7nb28y9dscbun98y4nvyy
    volumes:
      - ./app:/app
    container_name: user_expenses
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
